# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SplatAutover2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 366)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 70, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 100, 91, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 280, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.TransFile = QtWidgets.QLineEdit(self.centralwidget)
        self.TransFile.setGeometry(QtCore.QRect(200, 10, 113, 20))
        self.TransFile.setObjectName("TransFile")
        self.RecFile = QtWidgets.QLineEdit(self.centralwidget)
        self.RecFile.setGeometry(QtCore.QRect(200, 40, 113, 20))
        self.RecFile.setObjectName("RecFile")
        self.NoTrans = QtWidgets.QLineEdit(self.centralwidget)
        self.NoTrans.setGeometry(QtCore.QRect(200, 70, 113, 20))
        self.NoTrans.setObjectName("NoTrans")
        self.NoRec = QtWidgets.QLineEdit(self.centralwidget)
        self.NoRec.setGeometry(QtCore.QRect(200, 100, 113, 20))
        self.NoRec.setObjectName("NoRec")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 10, 101, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 40, 101, 21))
        self.label_6.setObjectName("label_6")
        self.NoRec_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.NoRec_2.setGeometry(QtCore.QRect(200, 200, 113, 20))
        self.NoRec_2.setObjectName("NoRec_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 200, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(320, 200, 101, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 140, 181, 16))
        self.label_9.setObjectName("label_9")
        self.NoRec_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.NoRec_3.setGeometry(QtCore.QRect(200, 140, 113, 20))
        self.NoRec_3.setObjectName("NoRec_3")
        self.NoRec_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.NoRec_4.setGeometry(QtCore.QRect(200, 170, 113, 20))
        self.NoRec_4.setObjectName("NoRec_4")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 170, 181, 16))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SPLAT Auto Ver1.0"))
        self.label.setText(_translate("MainWindow", "Please Select Transmit File:"))
        self.label_2.setText(_translate("MainWindow", "Please Select Receiver File:"))
        self.label_3.setText(_translate("MainWindow", "No. of Transmitters:"))
        self.label_4.setText(_translate("MainWindow", "No. of Receivers:"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.label_5.setText(_translate("MainWindow", "Include .csv or .txt"))
        self.label_6.setText(_translate("MainWindow", "Include .csv or .txt"))
        self.label_7.setText(_translate("MainWindow", "Output File Name"))
        self.label_8.setText(_translate("MainWindow", "Include .csv or .txt"))
        self.label_9.setText(_translate("MainWindow", "Trans height (include unit eg 150m)"))
        self.label_10.setText(_translate("MainWindow", "Receive height (include unit eg 150m)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

